########################
##### EXPERIMENTAL #####
########################

#####################################################################################################
#####                 NSPanel Easy - https://github.com/edwardtfn/NSPanel-Easy                  #####
#####################################################################################################
##### ESPHOME PRE-BUILT - Wall_Display variation by https://github.com/MichaelHeimann           #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
---
substitutions:
  device_name: "wall-display"
  friendly_name: "Wall Display"
  heater_relay: "1"  # Possible values: 1/2
  temp_min: "4"      # Min supported temperature
  temp_max: "27"     # Max supported temperature
  temp_step: "0.5"   # Temperature granularity

packages:
  prebuilt_package: !include nspanel_esphome_prebuilt.yaml
  climate_heat: !include ../esphome/nspanel_esphome_addon_climate_heat.yaml

dashboard_import:
  package_import_url: github://edwardtfn/NSPanel-Easy/prebuilt/wall_display.yaml@main
  import_full_config: false

esphome:
  project:
    name: edwardtfn.Wall_Display
  platformio_options:
    build_flags:
      - -D NSPANEL_EASY_PREBUILT_WALL_DISPLAY
text:
  - id: !extend fw_url
    initial_value: "https://raw.githubusercontent.com/edwardtfn/NSPanel-Easy/main/prebuilt/wall_display.bin"

update:
  - id: !extend update_std
    source: "https://raw.githubusercontent.com/edwardtfn/NSPanel-Easy/main/prebuilt/wall_display.manifest.json"
...
