substitutions:
  device_name: office-workstation-panel
  friendly_name: Office - Workstation - Panel
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

# bluetooth_proxy:

# logger:
#   level: VERY_VERBOSE

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: v4.3.30
    refresh: 30s
    files:
      - nspanel_esphome.yaml # Base package
      - nspanel_esphome_addon_climate_dual.yaml

  manual_ip: !include
    file: h:/esphome/packages/config_manual_ip.yaml
    vars:
      ip: !secret ip_office_workstation_panel

# wifi:
#   power_save_mode: LIGHT
